export interface Phrase {
  phrase: string;
  meaning: string;
  korean: string;
  /** Japanese / Chinese meaning. Optional: the card falls back to English. */
  ja?: string;
  zh?: string;
  example: string;
  category: "daily-life" | "work" | "social" | "media" | "food" | "sports";
}

export const phrases: Phrase[] = [
  // === DAILY LIFE (30 phrases) ===
  {
    phrase: "G'day",
    meaning: "Hello / Good day", ja: "こんにちは／こんにちは（日中の挨拶）", zh: "你好／日安",
    korean: "안녕하세요",
    example: "G'day mate, how's it going?",
    category: "daily-life",
  },
  {
    phrase: "How ya goin'?",
    meaning: "How are you? / How's it going?", ja: "お元気ですか？／調子はどう？", zh: "你好吗？／近来怎么样？",
    korean: "어떻게 지내세요?",
    example: "How ya goin'? Haven't seen you in ages!",
    category: "daily-life",
  },
  {
    phrase: "No worries",
    meaning: "No problem / It's fine / You're welcome", ja: "問題ないです／大丈夫です／どういたしまして", zh: "没问题／没事／不客气",
    korean: "괜찮아요 / 천만에요",
    example: "Thanks for helping out! — No worries, happy to help.",
    category: "daily-life",
  },
  {
    phrase: "Aye",
    meaning: "Hey / Excuse me (used to get attention)", ja: "すみません／ねえ（注意を引くときに使う）", zh: "嘿／打扰一下（用来引起注意）",
    korean: "저기요 / 야",
    example: "Aye, you dropped your wallet!",
    category: "daily-life",
  },
  {
    phrase: "Ta",
    meaning: "Thank you", ja: "ありがとう", zh: "谢谢",
    korean: "고마워 (가벼운 감사)",
    example: "Here's your coffee. — Ta, legend.",
    category: "daily-life",
  },
  {
    phrase: "Cheerio",
    meaning: "Goodbye / See ya", ja: "さようなら／またね", zh: "再见／回头见",
    korean: "잘 있어요",
    example: "Cheerio mate, see you tomorrow!",
    category: "daily-life",
  },
  {
    phrase: "Hooroo",
    meaning: "Goodbye", ja: "さようなら", zh: "再见",
    korean: "잘 가",
    example: "Hooroo, catch ya later!",
    category: "daily-life",
  },
  {
    phrase: "See ya later",
    meaning: "Goodbye (very common)", ja: "さようなら（非常によく使われる）", zh: "再见（非常常用）",
    korean: "나중에 봐요",
    example: "See ya later, don't be a stranger!",
    category: "daily-life",
  },
  {
    phrase: "Arvo",
    meaning: "Afternoon", ja: "午後", zh: "下午",
    korean: "오후",
    example: "Let's meet this arvo for a coffee.",
    category: "daily-life",
  },
  {
    phrase: "Sunnies",
    meaning: "Sunglasses", ja: "サングラス", zh: "太阳镜",
    korean: "선글라스",
    example: "Don't forget your sunnies — it's a scorcher today!",
    category: "daily-life",
  },
  {
    phrase: "Brolly",
    meaning: "Umbrella", ja: "傘", zh: "雨伞",
    korean: "우산",
    example: "Better grab your brolly, looks like rain.",
    category: "daily-life",
  },
  {
    phrase: "Thongs",
    meaning: "Flip-flops (not underwear)", ja: "ビーチサンダル（下着ではない）", zh: "人字拖（不是内衣）",
    korean: "쪼리 (슬리퍼)",
    example: "Throw on your thongs and let's head to the beach.",
    category: "daily-life",
  },
  {
    phrase: "Trackies",
    meaning: "Trackpants / Sweatpants", ja: "ジャージ／スウェットパンツ", zh: "运动裤／卫裤",
    korean: "트레이닝복 바지",
    example: "It's a lazy Sunday, so I'm wearing my trackies all day.",
    category: "daily-life",
  },
  {
    phrase: "Jumper",
    meaning: "Sweater / Pullover", ja: "セーター／プルオーバー", zh: "毛衣／套头衫",
    korean: "스웨터",
    example: "It's getting chilly — grab a jumper before we go out.",
    category: "daily-life",
  },
  {
    phrase: "Runners",
    meaning: "Sneakers / Trainers", ja: "スニーカー／運動靴", zh: "运动鞋／球鞋",
    korean: "운동화",
    example: "Wear your runners if we're walking to the station.",
    category: "daily-life",
  },
  {
    phrase: "Bottle-o",
    meaning: "Bottle shop / Liquor store", ja: "酒屋／酒類販売店", zh: "酒类专卖店／卖酒的店",
    korean: "주류 판매점",
    example: "We need to stop at the bottle-o before the party.",
    category: "daily-life",
  },
  {
    phrase: "Servo",
    meaning: "Service station / Petrol station", ja: "ガソリンスタンド", zh: "加油站",
    korean: "주유소",
    example: "Pull over at the next servo, I need to fill up.",
    category: "daily-life",
  },
  {
    phrase: "Maccas",
    meaning: "McDonald's", ja: "マクドナルド", zh: "麦当劳",
    korean: "맥도날드",
    example: "I'm craving a Maccas run after this game.",
    category: "daily-life",
  },
  {
    phrase: "Brekkie",
    meaning: "Breakfast", ja: "朝食", zh: "早餐",
    korean: "아침 식사",
    example: "What's for brekkie? I'm starving!",
    category: "daily-life",
  },
  {
    phrase: "Mozzie",
    meaning: "Mosquito", ja: "蚊", zh: "蚊子",
    korean: "모기",
    example: "The mozzies are crazy near the river at sunset.",
    category: "daily-life",
  },
  {
    phrase: "Bikkie",
    meaning: "Biscuit / Cookie", ja: "ビスケット／クッキー", zh: "饼干／曲奇",
    korean: "비스킷 / 쿠키",
    example: "Tim Tams are my favourite bikkie!",
    category: "daily-life",
  },
  {
    phrase: "Sanger",
    meaning: "Sandwich", ja: "サンドイッチ", zh: "三明治",
    korean: "샌드위치",
    example: "I'll grab a sanger from the cafe for lunch.",
    category: "daily-life",
  },
  {
    phrase: "Bottle of the cold stuff",
    meaning: "Beer / Cold drink", ja: "ビール／冷たい飲み物", zh: "啤酒／冷饮",
    korean: "맥주 / 시원한 음료",
    example: "Get us a bottle of the cold stuff from the esky!",
    category: "daily-life",
  },
  {
    phrase: "Esky",
    meaning: "Cooler / Ice box", ja: "クーラーボックス／アイスボックス", zh: "冷藏箱／冰桶",
    korean: "아이스박스",
    example: "Load up the esky with drinks for the barbie.",
    category: "daily-life",
  },
  {
    phrase: "Barbie",
    meaning: "Barbecue / BBQ", ja: "バーベキュー／BBQ", zh: "烧烤／BBQ",
    korean: "바베큐",
    example: "We're having a barbie this Saturday — you should come!",
    category: "daily-life",
  },
  {
    phrase: "Stubby holder",
    meaning: "Insulated can/bottle holder", ja: "断熱キャン・ボトルホルダー", zh: "保温罐／瓶套",
    korean: "캔 홀더",
    example: "Grab a stubby holder so your beer stays cold.",
    category: "daily-life",
  },
  {
    phrase: "Goon",
    meaning: "Cheap boxed wine", ja: "安いボックスワイン", zh: "便宜的盒装葡萄酒",
    korean: "박스 와인 (저렴한)",
    example: "We're bringing a bag of goon to the party.",
    category: "daily-life",
  },
  {
    phrase: "Roofy",
    meaning: "Roof rack (on a car)", ja: "ルーフラック（車の）", zh: "车顶行李架",
    korean: "차량용 루프랙",
    example: "We'll tie the surfboard to the roofy.",
    category: "daily-life",
  },
  {
    phrase: "Chuck a U-ey",
    meaning: "Make a U-turn", ja: "Uターンする", zh: "掉头",
    korean: "유턴하다",
    example: "We missed the turn — chuck a U-ey at the next lights.",
    category: "daily-life",
  },
  {
    phrase: "Flat out",
    meaning: "Very busy", ja: "とても忙しい", zh: "非常忙",
    korean: "완전 바쁜",
    example: "Sorry I haven't called, I've been flat out at work.",
    category: "daily-life",
  },

  // === WORK (30 phrases) ===
  {
    phrase: "How're ya going?",
    meaning: "How are you? (common workplace greeting)", ja: "お元気ですか？（職場でよく使う挨拶）", zh: "你好吗？（职场常见问候）",
    korean: "어떻게 지내세요? (직장 인사)",
    example: "Mornin', how're ya going today?",
    category: "work",
  },
  {
    phrase: "Fair dinkum",
    meaning: "Genuine / True / Honestly", ja: "本当に／本当だよ／正直に言うと", zh: "真的／确实／老实说",
    korean: "진짜로 / 정말이야",
    example: "Fair dinkum, that was the best presentation I've seen.",
    category: "work",
  },
  {
    phrase: "Stoked",
    meaning: "Very pleased / Thrilled", ja: "とても嬉しい／感激している", zh: "非常高兴／兴奋",
    korean: "완전 신난 / 너무 기쁜",
    example: "I'm stoked we got that contract signed.",
    category: "work",
  },
  {
    phrase: "Choc-a-block",
    meaning: "Completely full / Packed", ja: "満員／ぎっしり詰まった", zh: "满员／挤满了",
    korean: "가득 찬",
    example: "My schedule is choc-a-block this week.",
    category: "work",
  },
  {
    phrase: "She'll be right",
    meaning: "Everything will be fine / Don't worry", ja: "きっと大丈夫／心配しないで", zh: "一切都会好的／别担心",
    korean: "괜찮을 거야 / 걱정 마",
    example: "The report isn't perfect but she'll be right.",
    category: "work",
  },
  {
    phrase: "Ripper",
    meaning: "Excellent / Great thing", ja: "最高／素晴らしい", zh: "太好了／真棒",
    korean: "최고야 / 대단해",
    example: "That's a ripper idea for the project!",
    category: "work",
  },
  {
    phrase: "Whinge",
    meaning: "Complain (often about something minor)", ja: "不平を言う（ささいなことについてが多い）", zh: "抱怨（通常是小事）",
    korean: "불평하다 / 푸념하다",
    example: "Stop whinging about the coffee machine and just make a cup.",
    category: "work",
  },
  {
    phrase: "Keen",
    meaning: "Eager / Enthusiastic", ja: "やる気がある／熱心な", zh: "热切／热情",
    korean: "열정적인 / 원하는",
    example: "I'm keen to get started on the new system rollout.",
    category: "work",
  },
  {
    phrase: "Up to scratch",
    meaning: "Meeting the required standard", ja: "基準を満たしている", zh: "符合标准",
    korean: "기준에 맞는",
    example: "Your work this quarter hasn't been up to scratch.",
    category: "work",
  },
  {
    phrase: "Budge up",
    meaning: "Move over / Make room", ja: "少し詰めて／場所を空けて", zh: "挪一挪／腾点地方",
    korean: "좀 비켜줘 / 자리 좀 줘",
    example: "Budge up a bit so I can sit down too.",
    category: "work",
  },
  {
    phrase: "Crack on",
    meaning: "Continue / Get on with it", ja: "続ける／先に進む", zh: "继续／往下做",
    korean: "계속하다 / 진행하다",
    example: "Alright team, let's crack on with the meeting.",
    category: "work",
  },
  {
    phrase: "Hard yakka",
    meaning: "Hard work / Hard labour", ja: "きつい仕事／重労働", zh: "苦活／重体力劳动",
    korean: "힘든 일 / 고된 노동",
    example: "Moving those boxes all day was hard yakka.",
    category: "work",
  },
  {
    phrase: "A few roos loose in the top paddock",
    meaning: "A bit crazy / Not thinking clearly", ja: "ちょっとおかしい／頭が回っていない", zh: "有点疯／脑子不清楚",
    korean: "약간 정신이 나간",
    example: "He's got a few roos loose in the top paddock if he thinks that plan will work.",
    category: "work",
  },
  {
    phrase: "Dag",
    meaning: "Uncool person (affectionate)", ja: "ダサい人（親しみを込めて）", zh: "不酷的人（带点亲昵）",
    korean: "촌스러운 사람 (애정 섞인)",
    example: "You absolute dag — wearing socks with sandals to work!",
    category: "work",
  },
  {
    phrase: "Cuppa",
    meaning: "A cup of tea or coffee", ja: "紅茶かコーヒー1杯", zh: "一杯茶或咖啡",
    korean: "차 / 커피 한잔",
    example: "Let's grab a cuppa and chat about the proposal.",
    category: "work",
  },
  {
    phrase: "Bikkie time",
    meaning: "Tea/coffee break with biscuits", ja: "お茶／コーヒー休憩（ビスケット付き）", zh: "喝茶／咖啡的休息时间（配饼干）",
    korean: "간식 타임 (커피+과자)",
    example: "It's bikkie time — who wants a Tim Tam?",
    category: "work",
  },
  {
    phrase: "Dunny",
    meaning: "Toilet / Bathroom", ja: "トイレ／お手洗い", zh: "厕所／洗手间",
    korean: "화장실",
    example: "The dunny is down the hall on the left.",
    category: "work",
  },
  {
    phrase: "Dob in",
    meaning: "Report someone / Snitch", ja: "告げ口する／密告する", zh: "打小报告／告密",
    korean: "고자질하다",
    example: "Someone dobbed me in for taking a long lunch.",
    category: "work",
  },
  {
    phrase: "Ticket",
    meaning: "Fine / Penalty notice (or literal ticket)", ja: "罰金／違反切符（または文字通りのチケット）", zh: "罚款／罚单（或字面意义上的票）",
    korean: "범칙금 / 티켓",
    example: "Parking in that spot will get you a ticket.",
    category: "work",
  },
  {
    phrase: "Letter of the law",
    meaning: "Exactly following rules", ja: "規則を厳密に守る", zh: "严格按照规则办事",
    korean: "규정을 엄격히 지키는",
    example: "Our manager follows the letter of the law on break times.",
    category: "work",
  },
  {
    phrase: "Six and two threes",
    meaning: "Six of one, half a dozen of the other — same difference", ja: "どっちもどっち／同じようなもの", zh: "半斤八两——没什么区别",
    korean: "똑같은 / 거기서 거기",
    example: "Doing it today or tomorrow is six and two threes.",
    category: "work",
  },
  {
    phrase: "You're dreaming",
    meaning: "You're being unrealistic", ja: "夢を見すぎだよ／現実的じゃない", zh: "你太不现实了",
    korean: "꿈꾸는 거야 / 현실적이지 않아",
    example: "You want Friday off too? You're dreaming.",
    category: "work",
  },
  {
    phrase: "Sickie",
    meaning: "Sick day (sometimes a fake one)", ja: "病欠（たまに仮病）", zh: "病假（有时是装的）",
    korean: "병가 (가짜 병가 포함)",
    example: "He's been taking too many sickies on Mondays.",
    category: "work",
  },
  {
    phrase: "Get the sack",
    meaning: "Be fired / Dismissed", ja: "クビになる／解雇される", zh: "被炒鱿鱼／被解雇",
    korean: "해고되다",
    example: "If you're late again, you'll get the sack.",
    category: "work",
  },
  {
    phrase: "Bludge",
    meaning: "Laze around / Avoid work", ja: "ぶらぶらする／仕事をサボる", zh: "闲晃／偷懒不干活",
    korean: "빈둥거리다 / 일을 게을리하다",
    example: "Stop bludging and help us unload the truck.",
    category: "work",
  },
  {
    phrase: "Nuddy",
    meaning: "Naked (nude)", ja: "裸の（全裸）", zh: "裸体的（全裸）",
    korean: "벌거벗은 / 알몸의",
    example: "Changing rooms — no wandering around in the nuddy!",
    category: "work",
  },
  {
    phrase: "Coorie",
    meaning: "To cuddle / snuggle (or relax into someone)", ja: "寄り添う／くっつく（相手にもたれかかる）", zh: "依偎／搂抱（或靠向某人放松）",
    korean: "꼭 껴안다",
    example: "We all cooried up on the couch after the long drive.",
    category: "work",
  },
  {
    phrase: "Smoko",
    meaning: "Short break (originally for smokers, now anyone)", ja: "短い休憩（もとは喫煙者向け、今は誰でも）", zh: "短暂休息（原为烟民，现在谁都可以）",
    korean: "짧은 휴식 시간",
    example: "I'm heading out for smoko — want anything?",
    category: "work",
  },
  {
    phrase: "Rostered day off (RDO)",
    meaning: "A scheduled day off in a work cycle", ja: "勤務サイクルで予定された休日", zh: "工作周期中排定的休息日",
    korean: "예정된 휴무일",
    example: "I've got an RDO next Monday — long weekend!",
    category: "work",
  },
  {
    phrase: "Award rate",
    meaning: "Minimum hourly wage set by industry", ja: "業種ごとに定められた最低時給", zh: "按行业规定的最低时薪",
    korean: "업종별 최저 시급",
    example: "Check the award rate for hospitality workers before you take the job.",
    category: "work",
  },

  // === SOCIAL (30 phrases) ===
  {
    phrase: "Mate",
    meaning: "Friend / Buddy / Pal", ja: "友達／仲間", zh: "朋友／哥们",
    korean: "친구 / 동료",
    example: "Cheers mate, appreciate it!",
    category: "social",
  },
  {
    phrase: "Legend",
    meaning: "An amazing person", ja: "素晴らしい人", zh: "了不起的人",
    korean: "대단한 사람",
    example: "You're a legend for helping me move house.",
    category: "social",
  },
  {
    phrase: "Good onya",
    meaning: "Good for you / Well done", ja: "よかったね／よくやった", zh: "真为你高兴／干得好",
    korean: "잘했어 / 대단해",
    example: "You finished the marathon? Good onya!",
    category: "social",
  },
  {
    phrase: "Bloody oath",
    meaning: "Absolutely / Yes, definitely!", ja: "もちろん／間違いなく！", zh: "当然／绝对没错！",
    korean: "그럼요 / 당연하죠!",
    example: "Are we going to the pub after work? — Bloody oath!",
    category: "social",
  },
  {
    phrase: "Yeah nah",
    meaning: "No (polite disagreement or refusal)", ja: "いいえ（丁寧な反対や断り）", zh: "不（礼貌的反对或拒绝）",
    korean: "아니요 (정중한 거절)",
    example: "Wanna grab a beer? — Yeah nah, I've got an early start.",
    category: "social",
  },
  {
    phrase: "Nah yeah",
    meaning: "Yes (agreeing after thinking)", ja: "うん、そうだね（考えた末の同意）", zh: "好（考虑后同意）",
    korean: "응 그래 (생각 후 동의)",
    example: "D'you reckon the movie was good? — Nah yeah, it was alright.",
    category: "social",
  },
  {
    phrase: "Too easy",
    meaning: "No problem / Very easy", ja: "問題ない／とても簡単", zh: "没问题／很简单",
    korean: "쉬워요 / 문제없어요",
    example: "Can you grab my bag? — Too easy.",
    category: "social",
  },
  {
    phrase: "Chuck a sickie",
    meaning: "Take a fake sick day", ja: "仮病で休む", zh: "装病请假",
    korean: "가짜 병가를 내다",
    example: "We could chuck a sickie and go to the beach.",
    category: "social",
  },
  {
    phrase: "Rellies",
    meaning: "Relatives / Family members", ja: "親戚／家族", zh: "亲戚／家人",
    korean: "친척",
    example: "We're visiting the rellies in Newcastle this weekend.",
    category: "social",
  },
  {
    phrase: "Bogan",
    meaning: "An uncultured or unsophisticated person (stereotypical 'ocker')", ja: "教養のない人／洗練されていない人（典型的な「オッカー」）", zh: "没文化或不世故的人（刻板印象中的“奥克”）",
    korean: "촌뜨기 / 무식한 사람",
    example: "He's a bit of a bogan but he's a good bloke.",
    category: "social",
  },
  {
    phrase: "Bloke",
    meaning: "A man / Guy", ja: "男性／男", zh: "男人／男的",
    korean: "남자 / 사내",
    example: "He's a top bloke — always helps out.",
    category: "social",
  },
  {
    phrase: "Sheila",
    meaning: "A woman (somewhat dated but still used playfully)", ja: "女性（やや古いが今も冗談で使われる）", zh: "女人（有点过时，但仍有人开玩笑地用）",
    korean: "여자 (약간 구식이지만 장난스럽게 사용)",
    example: "That sheila's a ripper surfer.",
    category: "social",
  },
  {
    phrase: "Spit the dummy",
    meaning: "Get very angry / Throw a tantrum", ja: "ひどく怒る／かんしゃくを起こす", zh: "大发雷霆／发脾气",
    korean: "화를 내다 / 짜증내다",
    example: "He spat the dummy when he lost the game.",
    category: "social",
  },
  {
    phrase: "Fair go",
    meaning: "Give someone a chance / Be reasonable", ja: "チャンスをやれ／話がわかる人になれ", zh: "给个机会／讲点道理",
    korean: "기회를 줘 / 합리적으로 굴어",
    example: "Fair go mate, I only just got here!",
    category: "social",
  },
  {
    phrase: "Have a crack",
    meaning: "Try / Attempt something", ja: "やってみる／試す", zh: "试试／尝试",
    korean: "시도하다",
    example: "I'll have a crack at fixing the sink myself.",
    category: "social",
  },
  {
    phrase: "Hard lines",
    meaning: "Bad luck / Tough luck", ja: "残念だったね／運が悪いね", zh: "真倒霉／运气不好",
    korean: "안됐네 / 운이 없네",
    example: "You missed the bus? Hard lines.",
    category: "social",
  },
  {
    phrase: "Rage",
    meaning: "A big party / To party hard", ja: "大きなパーティー／派手に遊ぶ", zh: "大型派对／尽情狂欢",
    korean: "신나는 파티 / 마구 놀다",
    example: "We're going to rage at the festival this weekend.",
    category: "social",
  },
  {
    phrase: "Mad",
    meaning: "Very good / Cool (slang)", ja: "すごくいい／かっこいい（俗語）", zh: "非常好／酷（俚语）",
    korean: "완전 좋아 / 대박",
    example: "That gig was mad! Best band I've seen.",
    category: "social",
  },
  {
    phrase: "Suss",
    meaning: "Suspicious / Check something out (verb)", ja: "怪しい／様子を見る（動詞）", zh: "可疑／查看一下（动词）",
    korean: "수상한 / 살펴보다",
    example: "That guy looks suss. Let's suss him out.",
    category: "social",
  },
  {
    phrase: "Woop woop",
    meaning: "The middle of nowhere / A remote area", ja: "何もない辺ぴな場所／遠く離れた地域", zh: "前不着村后不着店的地方／偏远地区",
    korean: "외딴 곳 / 시골",
    example: "My aunt lives out woop woop — takes hours to get there.",
    category: "social",
  },
  {
    phrase: "Kick the bucket",
    meaning: "To die (humorous)", ja: "死ぬ（ユーモラスな表現）", zh: "死（幽默说法）",
    korean: "죽다 (우스운 표현)",
    example: "The old goldfish kicked the bucket last night.",
    category: "social",
  },
  {
    phrase: "Pull your head in",
    meaning: "Stop being annoying / Shut up", ja: "うるさいのをやめろ／黙れ", zh: "别烦人／闭嘴",
    korean: "좀 조용히 해 / 착각하지 마",
    example: "Pull your head in mate, nobody asked you.",
    category: "social",
  },
  {
    phrase: "Give it a burl",
    meaning: "Give it a try", ja: "試してみて", zh: "试一试",
    korean: "한번 해봐",
    example: "I've never kayaked before but I'll give it a burl.",
    category: "social",
  },
  {
    phrase: "Spewin'",
    meaning: "Very annoyed / Disappointed", ja: "すごくイライラした／がっかりした", zh: "非常恼怒／失望",
    korean: "완전 열받은 / 속상한",
    example: "I'm spewin' I missed the concert tickets.",
    category: "social",
  },
  {
    phrase: "Get off my back",
    meaning: "Stop bothering / nagging me", ja: "邪魔するのをやめて／小言を言うのをやめて", zh: "别烦我／别唠叨我",
    korean: "잔소리 그만해 / 좀 내버려둬",
    example: "Get off my back, I'll do it when I'm ready.",
    category: "social",
  },
  {
    phrase: "Stiff",
    meaning: "Unlucky (in a mild way)", ja: "ついていない（軽い意味で）", zh: "运气不好（较轻微）",
    korean: "운이 없는",
    example: "You got a flat tyre? That's stiff.",
    category: "social",
  },
  {
    phrase: "Chunder",
    meaning: "To vomit", ja: "吐く", zh: "呕吐",
    korean: "토하다",
    example: "He chundered after too many beers at the pub.",
    category: "social",
  },
  {
    phrase: "Froth",
    meaning: "Be very excited / Pumped", ja: "すごく興奮する／燃えている", zh: "非常兴奋／热血沸腾",
    korean: "완전 신나다",
    example: "I'm frothing for the footy grand final this weekend!",
    category: "social",
  },
  {
    phrase: "Cactus",
    meaning: "Broken / Not working / Dead", ja: "壊れた／動かない／死んでいる", zh: "坏了／不工作／废了",
    korean: "고장 난 / 망가진",
    example: "My phone went cactus after I dropped it in the pool.",
    category: "social",
  },

  // === FOOD & DRINKS (20 phrases) ===
  {
    phrase: "Chook",
    meaning: "Chicken", ja: "鶏肉", zh: "鸡肉",
    korean: "닭고기",
    example: "We're having chook for dinner tonight.",
    category: "food",
  },
  {
    phrase: "Parma / Chicken Parmi",
    meaning: "Chicken parmigiana — crumbed chicken with tomato sauce and cheese", ja: "チキン・パルミジャーナ — パン粉をつけた鶏肉にトマトソースとチーズ", zh: "帕尔玛干酪鸡排——裹面包糠的鸡肉配番茄酱和奶酪",
    korean: "치킨 파르마 (펍의 대표 메뉴)",
    example: "Nothing beats a parma and a beer at the local.",
    category: "food",
  },
  {
    phrase: "Snag",
    meaning: "Sausage (especially for BBQs)", ja: "ソーセージ（特にバーベキュー用）", zh: "香肠（特别是烧烤用）",
    korean: "소시지 (바베큐용)",
    example: "Flip the snags on the barbie, they're almost ready.",
    category: "food",
  },
  {
    phrase: "Tucker",
    meaning: "Food", ja: "食べ物", zh: "美食",
    korean: "음식",
    example: "What's for tucker tonight?",
    category: "food",
  },
  {
    phrase: "Servo feed",
    meaning: "Convenience store food / Petrol station snacks", ja: "コンビニの食べ物／ガソリンスタンドの軽食", zh: "便利店食物／加油站的零食",
    korean: "주유소 음식 /편의점 음식",
    example: "We survived on servo feeds during the road trip.",
    category: "food",
  },
  {
    phrase: "Damper",
    meaning: "Traditional Australian bread made from flour and water", ja: "小麦粉と水で作るオーストラリアの伝統的なパン", zh: "用面粉和水做的澳大利亚传统面包",
    korean: "호주 전통 빵 (밀가루와 물로 만든)",
    example: "We made damper over the campfire — rustic but delicious.",
    category: "food",
  },
  {
    phrase: "Meat pie",
    meaning: "A classic Aussie fast food — flaky pastry filled with meat", ja: "オーストラリアの定番ファストフード — 肉が詰まったサクサクのパイ", zh: "经典的澳洲快餐——填满肉馅的酥皮点心",
    korean: "호주의 대표 패스트푸드 — 속이 고기인 페이스트리",
    example: "Grab me a meat pie from the bakery, would ya?",
    category: "food",
  },
  {
    phrase: "Dim sim",
    meaning: "A large, deep-fried dim sum popular in Victoria", ja: "ビクトリアで人気の大きな揚げ点心", zh: "在维多利亚州很受欢迎的油炸大点心",
    korean: "빨리 튀긴 딤섬 (빅토리아에서 유행)",
    example: "Dim sims from the chippy are the ultimate comfort food.",
    category: "food",
  },
  {
    phrase: "Cheese on toast",
    meaning: "Simple comfort food — melted cheese on toasted bread", ja: "簡単な癒しの食べ物 — トーストしたパンに溶けたチーズ", zh: "简单的暖心食物——烤面包上放融化的奶酪",
    korean: "간단한 음식 — 토스트에 녹인 치즈",
    example: "Late night cheese on toast hits different after a few drinks.",
    category: "food",
  },
  {
    phrase: "Sevo",
    meaning: "To serve drinks at a party / Work behind the bar", ja: "パーティーで飲み物を出す／バーで働く", zh: "在派对上端饮品／在吧台工作",
    korean: "파티에서 음료 제공 / 바에서 일하기",
    example: "Who can sevo tonight? We need someone on the drinks.",
    category: "food",
  },

  // === SPORTS (20 phrases) ===
  {
    phrase: "Footy",
    meaning: "Football (AFL or Rugby League depending on the state)", ja: "フットボール（州によってAFLまたはラグビーリーグ）", zh: "橄榄球（视州而定是AFL或橄榄球联赛）",
    korean: "풋볼 (주에 따라 AFL 또는 럭비 리그)",
    example: "Are you watching the footy tonight? Go the Blues!",
    category: "sports",
  },
  {
    phrase: "The AFL",
    meaning: "Australian Football League — the big Aussie rules football comp", ja: "オーストラリアン・フットボール・リーグ — オージー・ルールズ最大の大会", zh: "澳大利亚足球联赛——最大的澳式橄榄球赛事",
    korean: "호주식 축구 리그",
    example: "The AFL season kicks off in March.",
    category: "sports",
  },
  {
    phrase: "The NRL",
    meaning: "National Rugby League — rugby league football", ja: "ナショナル・ラグビー・リーグ — ラグビーリーグ", zh: "全国橄榄球联赛——橄榄球联赛",
    korean: "내셔널 럭비 리그",
    example: "NRL grand final is one of the biggest sporting events in Australia.",
    category: "sports",
  },
  {
    phrase: "The Ashes",
    meaning: "Cricket series between Australia and England", ja: "オーストラリアとイングランドのクリケット・シリーズ", zh: "澳大利亚与英格兰之间的板球系列赛",
    korean: "호주 vs 영국 크리켓 시리즈",
    example: "We won The Ashes again! Three-nil!",
    category: "sports",
  },
  {
    phrase: "The Big Bash",
    meaning: "BBL — popular Twenty20 cricket league in summer", ja: "BBL — 夏に人気のトゥエンティ20クリケットリーグ", zh: "BBL——夏季大受欢迎的二十20板球联赛",
    korean: "여름 크리켓 리그",
    example: "Let's watch the Big Bash on the big screen.",
    category: "sports",
  },
  {
    phrase: "Wicket",
    meaning: "The stumps (target for bowler) or the dismissal of a batsman", ja: "ウィケット（投手の的）または打者のアウト", zh: "三柱门（投球手的目标）或击球手出局",
    korean: "wicket (크리켓의 삼대) / 타자 아웃",
    example: "What a ripper catch at the wicket!",
    category: "sports",
  },
  {
    phrase: "Heaps",
    meaning: "A lot / Lots of (casual sports talk)", ja: "たくさん／いっぱい（カジュアルなスポーツ談義）", zh: "很多／超多（随意的体育闲聊）",
    korean: "많이 / 상당히",
    example: "There's heaps of good players in this team.",
    category: "sports",
  },
  {
    phrase: "Sledging",
    meaning: "Trash talk between players (especially in cricket)", ja: "選手同士の挑発的な言葉（特にクリケットで）", zh: "球员之间的垃圾话（尤其在板球中）",
    korean: "상대편 약 올리기 (특히 크리켓)",
    example: "The Aussie team is known for their sledging.",
    category: "sports",
  },
  {
    phrase: "The Wallabies",
    meaning: "Australia's national rugby union team", ja: "オーストラリアのラグビーユニオン代表チーム", zh: "澳大利亚国家橄榄球（联盟式）代表队",
    korean: "호주 럭비 유니온 국가대표",
    example: "The Wallabies have a big match against New Zealand next week.",
    category: "sports",
  },
  {
    phrase: "The Socceroos",
    meaning: "Australia's national soccer team", ja: "オーストラリアのサッカー代表チーム", zh: "澳大利亚国家足球队",
    korean: "호주 축구 국가대표",
    example: "Go the Socceroos! World Cup qualifier coming up.",
    category: "sports",
  },
  {
    phrase: "The Matildas",
    meaning: "Australia's women's national soccer team", ja: "オーストラリア女子サッカー代表チーム", zh: "澳大利亚女子国家足球队",
    korean: "호주 여자 축구 국가대표",
    example: "The Matildas are bringing home the gold!",
    category: "sports",
  },
  {
    phrase: "Oppo",
    meaning: "Opposition team / opponent", ja: "相手チーム／対戦相手", zh: "对方球队／对手",
    korean: "상대팀 / 라이벌",
    example: "We need to shut down their oppo's best player.",
    category: "sports",
  },
  {
    phrase: "Sesh",
    meaning: "Session / Training session / Practice", ja: "セッション／トレーニング／練習", zh: "训练课／训练／练习",
    korean: "세션 / 훈련 / 연습",
    example: "Hit the gym for a sesh before the game.",
    category: "sports",
  },
  {
    phrase: "Squad",
    meaning: "Team / Group of players", ja: "チーム／選手団", zh: "球队／队员",
    korean: "팀 / 선수단",
    example: "The coach is picking the squad for Saturday.",
    category: "sports",
  },
  {
    phrase: "The pool",
    meaning: "Gym pool for swimming / The swimming team", ja: "ジムのプール／水泳チーム", zh: "健身房泳池／游泳队",
    korean: "헬스장 수영장 / 수영팀",
    example: "I've got a session at the pool at 6am.",
    category: "sports",
  },
  {
    phrase: "Champs",
    meaning: "Championships / Final competition", ja: "選手権／決勝", zh: "锦标赛／决赛",
    korean: "챔피언십 / 결승",
    example: "We're heading to champs next weekend!",
    category: "sports",
  },
  {
    phrase: "Cashed up",
    meaning: "Having plenty of money (used in gambling contexts)", ja: "お金がたくさんある（ギャンブルの文脈で使用）", zh: "很有钱（用于赌博语境）",
    korean: "돈이 많은 / 여유가 있는",
    example: "He's cashed up after that big win.",
    category: "sports",
  },
  {
    phrase: "Sponsorship",
    meaning: "When a sports player is backed financially by a company", ja: "スポーツ選手が企業から資金援助を受けているとき", zh: "运动员获得公司资金赞助",
    korean: "스폰서십 / 기업 후원",
    example: "She's got a big sponsorship deal with Nike.",
    category: "sports",
  },
  {
    phrase: "Rookie",
    meaning: "A new or inexperienced player", ja: "新人／経験の浅い選手", zh: "新人／缺乏经验的球员",
    korean: "신인 /경험 부족한 선수",
    example: "He's a rookie but he's showing a lot of potential.",
    category: "sports",
  },

  // === MEDIA (30 phrases) ===
  {
    phrase: "Sledge",
    meaning: "To tease / insult playfully (especially in sports)", ja: "からかう／冗談めかして挑発する（特にスポーツで）", zh: "调侃／开玩笑地挑衅（尤指体育中）",
    korean: "약 올리다 (스포츠에서)",
    example: "The crowd was sledging the batsman all afternoon.",
    category: "media",
  },
  {
    phrase: "Tip",
    meaning: "Prediction (especially for sports results)", ja: "予想（特にスポーツの結果）", zh: "预测（尤指比赛结果）",
    korean: "예측 (스포츠 결과)",
    example: "Who's your tip for the Melbourne Cup?",
    category: "media",
  },
  {
    phrase: "Garbo",
    meaning: "Garbage collector / Bin day", ja: "ごみ収集人／ごみ収集日", zh: "垃圾清运工／收垃圾日",
    korean: "쓰레기 수거일 / 수거원",
    example: "Don't forget to put the bins out — garbo comes Thursday.",
    category: "media",
  },
  {
    phrase: "Postie",
    meaning: "Postman / Postal delivery worker", ja: "郵便配達員", zh: "邮递员／邮政投递员",
    korean: "우편 배달부",
    example: "The postie's already come — there's a parcel for you.",
    category: "media",
  },
  {
    phrase: "Journo",
    meaning: "Journalist", ja: "記者", zh: "记者",
    korean: "기자",
    example: "The journo from Channel 9 is doing a story on our suburb.",
    category: "media",
  },
  {
    phrase: "Tradie",
    meaning: "Tradesperson (builder, electrician, plumber, etc.)", ja: "職人（建設、電気、配管など）", zh: "技工（建筑工、电工、水管工等）",
    korean: "기술자 (건축, 전기, 배관 등)",
    example: "The tradies are starting on the renovation tomorrow.",
    category: "media",
  },
  {
    phrase: "Ambo",
    meaning: "Ambulance / Paramedic", ja: "救急車／救急救命士", zh: "救护车／急救员",
    korean: "구급차 / 구급대원",
    example: "Quick, call an ambo — someone's been hurt!",
    category: "media",
  },
  {
    phrase: "On the box",
    meaning: "On TV", ja: "テレビで放送中", zh: "在电视上播出",
    korean: "TV에서 방영 중인",
    example: "What's on the box tonight? Anything good?",
    category: "media",
  },
  {
    phrase: "Do a Bradbury",
    meaning: "Win unexpectedly (from Steven Bradbury's 2002 gold)", ja: "思いがけず勝つ（スティーブン・ブラッドベリの2002年優勝から）", zh: "意外获胜（源自史蒂文·布拉德伯里2002年夺金）",
    korean: "뜻밖에 이기다 / 운으로 이기다",
    example: "Our team did a Bradbury and snuck into the finals.",
    category: "media",
  },
  {
    phrase: "Going viral",
    meaning: "Spreading rapidly online", ja: "ネットで急速に拡散している", zh: "在网上迅速传播",
    korean: "바이럴 되다",
    example: "That video of the quokka went viral on TikTok.",
    category: "media",
  },
  {
    phrase: "DM",
    meaning: "Direct Message", ja: "ダイレクトメッセージ", zh: "私信",
    korean: "다이렉트 메시지",
    example: "DM me the details and I'll check it out.",
    category: "media",
  },
  {
    phrase: "Slide into DMs",
    meaning: "Send someone a private message (often romantically)", ja: "誰かに個別メッセージを送る（しばしば恋愛的な意味で）", zh: "给别人发私信（常带有恋爱意味）",
    korean: "DM 보내다 (종종 이성적으로)",
    example: "He slid into her DMs and now they're dating.",
    category: "media",
  },
  {
    phrase: "Finsta",
    meaning: "Fake Instagram account (private, for close friends)", ja: "偽のInstagramアカウント（親しい友人向けの非公開アカウント）", zh: "假的Instagram账号（私下给密友用的）",
    korean: "가짜 인스타그램 계정 (친한 친구용)",
    example: "Follow my finsta for the real content.",
    category: "media",
  },
  {
    phrase: "Rinsta",
    meaning: "Real Instagram account (public-facing)", ja: "本当のInstagramアカウント（公開用）", zh: "真实的Instagram账号（对外公开）",
    korean: "진짜 인스타그램 계정 (대중 공개용)",
    example: "I only post my best photos on my rinsta.",
    category: "media",
  },
  {
    phrase: "Ghost",
    meaning: "To suddenly stop all communication", ja: "突然すべての連絡を絶つ", zh: "突然断绝一切联系",
    korean: "잠수 타다 / 연락 끊다",
    example: "We went on three dates and then she ghosted me.",
    category: "media",
  },
  {
    phrase: "Stan",
    meaning: "An obsessive fan (from Eminem song)", ja: "熱狂的なファン（エミネムの曲から）", zh: "痴迷的粉丝（源自埃米纳姆的歌曲）",
    korean: "열성 팬",
    example: "I'm a total stan of that Australian singer.",
    category: "media",
  },
  {
    phrase: "Ratio",
    meaning: "When replies outnumber likes (bad for the original post)", ja: "返信がいいねより多いとき（元の投稿にとって良くない）", zh: "回复数超过点赞数（对原帖不利）",
    korean: "댓글이 좋아요보다 많음 (안 좋은 의미)",
    example: "That take was so bad they got ratio'd into oblivion.",
    category: "media",
  },
  {
    phrase: "Banger",
    meaning: "A very good song / track", ja: "とても良い曲／トラック", zh: "非常好听的歌／曲目",
    korean: "명곡 / 대박 노래",
    example: "This new album is full of bangers.",
    category: "media",
  },
  {
    phrase: "Aussie rules footy",
    meaning: "Australian Rules Football (AFL)", ja: "オーストラリア式フットボール（AFL）", zh: "澳式足球（AFL）",
    korean: "호주식 풋볼 (AFL)",
    example: "Aussie rules footy is the most popular sport in Victoria.",
    category: "media",
  },
  {
    phrase: "Spill the tea",
    meaning: "Share gossip / Reveal drama", ja: "ゴシップを話す／噂を暴露する", zh: "分享八卦／爆料",
    korean: "가십을 털어놓다",
    example: "Spill the tea about what happened at the party!",
    category: "media",
  },
  {
    phrase: "Lit",
    meaning: "Amazing / Exciting / Fun", ja: "すごい／わくわくする／楽しい", zh: "太棒了／刺激／好玩",
    korean: "완전 신나는 / 대박",
    example: "The concert was lit — best night ever!",
    category: "media",
  },
  {
    phrase: "Cap / No cap",
    meaning: "Lie / No lie (internet slang now used by Australians too)", ja: "嘘／本当（今はオーストラリア人も使うネットスラング）", zh: "撒谎／不骗你（如今澳大利亚人也用的网络俚语）",
    korean: "거짓말 / 진짜로",
    example: "No cap, that was the best burger I've ever had.",
    category: "media",
  },
  {
    phrase: "Sus",
    meaning: "Suspicious / Shady", ja: "怪しい／いかがわしい", zh: "可疑／不靠谱",
    korean: "수상한",
    example: "That account looks sus — probably a bot.",
    category: "media",
  },
  {
    phrase: "FYP",
    meaning: "For You Page (TikTok homepage feed)", ja: "おすすめページ（TikTokのホームフィード）", zh: "推荐页（TikTok首页信息流）",
    korean: "틱톡 메인 피드",
    example: "This recipe keeps showing up on my FYP.",
    category: "media",
  },
  {
    phrase: "OOMF",
    meaning: "One Of My Followers", ja: "私のフォロワーの一人", zh: "我的一个粉丝",
    korean: "내 팔로워 중 한 명",
    example: "OOMF posted the funniest meme today.",
    category: "media",
  },
  {
    phrase: "Lowkey",
    meaning: "Quietly / Secretly / Sort of", ja: "密かに／こっそり／どことなく", zh: "悄悄地／偷偷地／有点",
    korean: "은근히 / 슬쩍",
    example: "I'm lowkey obsessed with this K-drama.",
    category: "media",
  },
  {
    phrase: "Highkey",
    meaning: "Openly / Very much", ja: "堂々と／とても", zh: "公开地／非常",
    korean: "완전 / 대놓고",
    example: "I highkey need a coffee right now.",
    category: "media",
  },

  {
    phrase: "Aggro",
    meaning: "Aggressive / anger", ja: "攻撃的／怒り", zh: "咄咄逼人／愤怒",
    korean: "약올림 / 공격적",
    example: "Don't get aggro about it, it's just a bit of banter.",
    category: "daily-life",
  },
  {
    phrase: "Ankle-biter",
    meaning: "A small child", ja: "小さな子ども", zh: "小孩",
    korean: "꼬마 애",
    example: "Watch where you're driving, there are ankle-biters about.",
    category: "daily-life",
  },
  {
    phrase: "Avo",
    meaning: "Avocado", ja: "アボカド", zh: "牛油果",
    korean: "아보카도",
    example: "Smashed avo on toast is like $18 AUD at most places now.",
    category: "daily-life",
  },
  {
    phrase: "Chinwag",
    meaning: "A chat / a good conversation", ja: "おしゃべり／楽しい会話", zh: "闲聊／愉快的交谈",
    korean: "수다 / 잡담",
    example: "Had a proper chinwag with Dave at the pub last night.",
    category: "social",
  },
  {
    phrase: "Countermeal",
    meaning: "Free or subsidised meal provided to workers", ja: "労働者に提供される無料または補助された食事", zh: "提供给员工的免费或补贴餐食",
    korean: "직장에서 제공하는 무료/할인 식사",
    example: "The job came with a company car and countermeals, not bad.",
    category: "work",
  },
  {
    phrase: "Dairy",
    meaning: "A corner shop / convenience store", ja: "街角の商店／コンビニ", zh: "街角小店／便利店",
    korean: "편의점",
    example: "Grab some milk from the dairy on the corner.",
    category: "daily-life",
  },
  {
    phrase: "Dead horse",
    meaning: "Tomato sauce / ketchup", ja: "トマトソース／ケチャップ", zh: "番茄酱",
    korean: "토마토 케첩",
    example: "Pass the dead horse, my chips are dry.",
    category: "daily-life",
  },
  {
    phrase: "Devo",
    meaning: "Devastated / really disappointed", ja: "打ちのめされた／ひどく失望した", zh: "心碎／非常失望",
    korean: "너무 실망한 / 허탈한",
    example: "I'm absolutely devo, the concert got cancelled.",
    category: "social",
  },
  {
    phrase: "Digger",
    meaning: "An Australian soldier; also a friendly term for an Aussie bloke", ja: "オーストラリアの兵士。オーストラリア人男性への親しみある呼び方でもある", zh: "澳大利亚士兵；也是对澳大利亚男性的亲切称呼",
    korean: "호주 병사 / 호주 남자",
    example: "He was a true blue digger, fought in two wars.",
    category: "social",
  },
  {
    phrase: "Hoon",
    meaning: "A reckless driver or hooligan", ja: "無謀な運転手または不良", zh: "鲁莽的司机或小混混",
    korean: "무법운전자",
    example: "Some hoon did a burnout on our street last night.",
    category: "daily-life",
  },
  {
    phrase: "Hump day",
    meaning: "Wednesday (mid-week)", ja: "水曜日（週の半ば）", zh: "星期三（周中）",
    korean: "주중 중반 (수요일)",
    example: "Hump day! Two more days until the weekend.",
    category: "daily-life",
  },
  {
    phrase: "Kindie",
    meaning: "Kindergarten / childcare", ja: "幼稚園／保育園", zh: "幼儿园／托儿所",
    korean: "유치원 / 보육원",
    example: "Drop the kids at kindie on the way to work.",
    category: "daily-life",
  },
  {
    phrase: "Lappy",
    meaning: "Laptop computer", ja: "ノートパソコン", zh: "笔记本电脑",
    korean: "노트북",
    example: "Can you jump on your lappy and fix that spreadsheet?",
    category: "daily-life",
  },
  {
    phrase: "Longneck",
    meaning: "A 750ml bottle of beer", ja: "750mlのビール1本", zh: "一瓶750ml啤酒",
    korean: "750ml 맥주병",
    example: "Grab us a slab of longnecks from the bottle-o.",
    category: "social",
  },
  {
    phrase: "Middy",
    meaning: "A 285ml glass of beer (NSW)", ja: "ビール285ml（NSW）", zh: "285毫升啤酒（新南威尔士州）",
    korean: "285ml 생맥주",
    example: "Two middies and a schooner of pale ale, please.",
    category: "social",
  },
  {
    phrase: "Muster",
    meaning: "To gather together", ja: "集まる", zh: "聚在一起",
    korean: "모이다",
    example: "Let's muster up everyone and head to the pub.",
    category: "social",
  },
  {
    phrase: "Maz",
    meaning: "A mate / a good friend", ja: "仲間／親友", zh: "伙伴／好朋友",
    korean: "친구 / 동료",
    example: "Good on ya maz, that was a bloody good idea.",
    category: "social",
  },
  {
    phrase: "Op shop",
    meaning: "Opportunity shop / charity thrift store", ja: "リサイクルショップ／チャリティー古着店", zh: "二手商店／慈善旧货店",
    korean: "재활용 옷가게",
    example: "Got this jacket for $5 AUD at the op shop.",
    category: "daily-life",
  },
  {
    phrase: "Pash",
    meaning: "A passionate kiss", ja: "情熱的なキス", zh: "热烈的吻",
    korean: "열정적인 키스",
    example: "They had a bit of a pash at the party.",
    category: "social",
  },
  {
    phrase: "Pokies",
    meaning: "Poker machines / slot machines in pubs and clubs", ja: "パブやクラブにあるポーカー機／スロットマシン", zh: "酒吧和俱乐部里的老虎机",
    korean: "포커머신 / 슬롯머신",
    example: "Lost $50 AUD on the pokies in 10 minutes. Classic.",
    category: "social",
  },
  {
    phrase: "Prezzie",
    meaning: "Present / gift", ja: "プレゼント／贈り物", zh: "礼物",
    korean: "선물",
    example: "Thanks for the prezzie, you shouldn't have!",
    category: "daily-life",
  },
  {
    phrase: "Proper",
    meaning: "Really / truly / genuine", ja: "本当に／まさに／本物の", zh: "真的／确实／货真价实",
    korean: "정말로 / 제대로",
    example: "That was a proper feed, I couldn't move after.",
    category: "daily-life",
  },
  {
    phrase: "Salvos",
    meaning: "Salvation Army charity shop", ja: "救世軍のチャリティーショップ", zh: "救世军慈善商店",
    korean: "구원군 자선 매장",
    example: "Got some decent clothes from the salvos for under $20 AUD.",
    category: "daily-life",
  },
  {
    phrase: "Schooner",
    meaning: "A 425ml glass of beer (NSW)", ja: "ビール425ml（NSW）", zh: "425毫升啤酒（新南威尔士州）",
    korean: "425ml 생맥주",
    example: "One schooner of XXXX please, mate.",
    category: "social",
  },
  {
    phrase: "Scull",
    meaning: "To drink a beer very quickly", ja: "ビールを一気に飲む", zh: "快速喝掉一杯啤酒",
    korean: "한 손에 들고 한 모금에 마시다",
    example: "He skulled his beer in about three seconds flat.",
    category: "social",
  },
  {
    phrase: "Shonky",
    meaning: "Not quite right / dodgy / unreliable", ja: "いまいち／怪しい／当てにならない", zh: "不太对劲／不可靠／靠不住",
    korean: "딱히 좋지 않은 / 의심스러운",
    example: "That tradie seems a bit shonky, I'd get another quote.",
    category: "daily-life",
  },
  {
    phrase: "Skinny",
    meaning: "A latte or flat white in a 180ml cup", ja: "180mlカップのラテまたはフラットホワイト", zh: "180毫升杯装拿铁或馥芮白",
    korean: "스키니 라떼",
    example: "Skinny flat white, two sugars thanks.",
    category: "daily-life",
  },
  {
    phrase: "Slab",
    meaning: "A carton of 24 beers", ja: "ビール24本入りケース", zh: "一箱24瓶啤酒",
    korean: "맥주 24개입 칩",
    example: "Grab a slab on the way to the BBQ.",
    category: "social",
  },
  {
    phrase: "Spruiker",
    meaning: "A person who advertises / calls out deals on the street", ja: "街で宣伝したり特売を呼びかける人", zh: "在街头宣传／吆喝促销的人",
    korean: "길거리 광고인",
    example: "Watch out for the spruiker outside the shop, he'll trap you in.",
    category: "daily-life",
  },
  {
    phrase: "Tinny",
    meaning: "A small can of beer", ja: "小さい缶ビール1本", zh: "一小罐啤酒",
    korean: "소형 맥주 캔",
    example: "Grab a tinny from the esky on the way.",
    category: "social",
  },
  {
    phrase: "Trackie daks",
    meaning: "Track pants / sweatpants", ja: "トラックパンツ／スウェットパンツ", zh: "运动裤／休闲裤",
    korean: "트랙바지",
    example: "Can't go to the shops in trackie daks, that's bogan behaviour.",
    category: "daily-life",
  },
  {
    phrase: "Ute",
    meaning: "Utility vehicle / pickup truck", ja: "ユーティリティ車／ピックアップトラック", zh: "多用途车／皮卡车",
    korean: "밴 / 픽업트럭",
    example: "Throw the esky in the ute, we're heading to the beach.",
    category: "daily-life",
  },
  {
    phrase: "Yonks",
    meaning: "A long time", ja: "長い間", zh: "很长时间",
    korean: "오래 / 한참",
    example: "I haven't seen Dave in yonks, he moved to Melbourne.",
    category: "daily-life",
  }
];