export interface Phrase {
  phrase: string;
  meaning: string;
  korean: string;
  example: string;
  category: "daily-life" | "work" | "social" | "media";
}

export const phrases: Phrase[] = [
  // === DAILY LIFE (30 phrases) ===
  {
    phrase: "G'day",
    meaning: "Hello / Good day",
    korean: "안녕하세요",
    example: "G'day mate, how's it going?",
    category: "daily-life",
  },
  {
    phrase: "How ya goin'?",
    meaning: "How are you? / How's it going?",
    korean: "어떻게 지내세요?",
    example: "How ya goin'? Haven't seen you in ages!",
    category: "daily-life",
  },
  {
    phrase: "No worries",
    meaning: "No problem / It's fine / You're welcome",
    korean: "괜찮아요 / 천만에요",
    example: "Thanks for helping out! — No worries, happy to help.",
    category: "daily-life",
  },
  {
    phrase: "Aye",
    meaning: "Hey / Excuse me (used to get attention)",
    korean: "저기요 / 야",
    example: "Aye, you dropped your wallet!",
    category: "daily-life",
  },
  {
    phrase: "Ta",
    meaning: "Thank you",
    korean: "고마워 (가벼운 감사)",
    example: "Here's your coffee. — Ta, legend.",
    category: "daily-life",
  },
  {
    phrase: "Cheerio",
    meaning: "Goodbye / See ya",
    korean: "잘 있어요",
    example: "Cheerio mate, see you tomorrow!",
    category: "daily-life",
  },
  {
    phrase: "Hooroo",
    meaning: "Goodbye",
    korean: "잘 가",
    example: "Hooroo, catch ya later!",
    category: "daily-life",
  },
  {
    phrase: "See ya later",
    meaning: "Goodbye (very common)",
    korean: "나중에 봐요",
    example: "See ya later, don't be a stranger!",
    category: "daily-life",
  },
  {
    phrase: "Arvo",
    meaning: "Afternoon",
    korean: "오후",
    example: "Let's meet this arvo for a coffee.",
    category: "daily-life",
  },
  {
    phrase: "Sunnies",
    meaning: "Sunglasses",
    korean: "선글라스",
    example: "Don't forget your sunnies — it's a scorcher today!",
    category: "daily-life",
  },
  {
    phrase: "Brolly",
    meaning: "Umbrella",
    korean: "우산",
    example: "Better grab your brolly, looks like rain.",
    category: "daily-life",
  },
  {
    phrase: "Thongs",
    meaning: "Flip-flops (not underwear)",
    korean: "쪼리 (슬리퍼)",
    example: "Throw on your thongs and let's head to the beach.",
    category: "daily-life",
  },
  {
    phrase: "Trackies",
    meaning: "Trackpants / Sweatpants",
    korean: "트레이닝복 바지",
    example: "It's a lazy Sunday, so I'm wearing my trackies all day.",
    category: "daily-life",
  },
  {
    phrase: "Jumper",
    meaning: "Sweater / Pullover",
    korean: "스웨터",
    example: "It's getting chilly — grab a jumper before we go out.",
    category: "daily-life",
  },
  {
    phrase: "Runners",
    meaning: "Sneakers / Trainers",
    korean: "운동화",
    example: "Wear your runners if we're walking to the station.",
    category: "daily-life",
  },
  {
    phrase: "Bottle-o",
    meaning: "Bottle shop / Liquor store",
    korean: "주류 판매점",
    example: "We need to stop at the bottle-o before the party.",
    category: "daily-life",
  },
  {
    phrase: "Servo",
    meaning: "Service station / Petrol station",
    korean: "주유소",
    example: "Pull over at the next servo, I need to fill up.",
    category: "daily-life",
  },
  {
    phrase: "Maccas",
    meaning: "McDonald's",
    korean: "맥도날드",
    example: "I'm craving a Maccas run after this game.",
    category: "daily-life",
  },
  {
    phrase: "Brekkie",
    meaning: "Breakfast",
    korean: "아침 식사",
    example: "What's for brekkie? I'm starving!",
    category: "daily-life",
  },
  {
    phrase: "Mozzie",
    meaning: "Mosquito",
    korean: "모기",
    example: "The mozzies are crazy near the river at sunset.",
    category: "daily-life",
  },
  {
    phrase: "Bikkie",
    meaning: "Biscuit / Cookie",
    korean: "비스킷 / 쿠키",
    example: "Tim Tams are my favourite bikkie!",
    category: "daily-life",
  },
  {
    phrase: "Sanger",
    meaning: "Sandwich",
    korean: "샌드위치",
    example: "I'll grab a sanger from the cafe for lunch.",
    category: "daily-life",
  },
  {
    phrase: "Bottle of the cold stuff",
    meaning: "Beer / Cold drink",
    korean: "맥주 / 시원한 음료",
    example: "Get us a bottle of the cold stuff from the esky!",
    category: "daily-life",
  },
  {
    phrase: "Esky",
    meaning: "Cooler / Ice box",
    korean: "아이스박스",
    example: "Load up the esky with drinks for the barbie.",
    category: "daily-life",
  },
  {
    phrase: "Barbie",
    meaning: "Barbecue / BBQ",
    korean: "바베큐",
    example: "We're having a barbie this Saturday — you should come!",
    category: "daily-life",
  },
  {
    phrase: "Stubby holder",
    meaning: "Insulated can/bottle holder",
    korean: "캔 홀더",
    example: "Grab a stubby holder so your beer stays cold.",
    category: "daily-life",
  },
  {
    phrase: "Goon",
    meaning: "Cheap boxed wine",
    korean: "박스 와인 (저렴한)",
    example: "We're bringing a bag of goon to the party.",
    category: "daily-life",
  },
  {
    phrase: "Roofy",
    meaning: "Roof rack (on a car)",
    korean: "차량용 루프랙",
    example: "We'll tie the surfboard to the roofy.",
    category: "daily-life",
  },
  {
    phrase: "Chuck a U-ey",
    meaning: "Make a U-turn",
    korean: "유턴하다",
    example: "We missed the turn — chuck a U-ey at the next lights.",
    category: "daily-life",
  },
  {
    phrase: "Flat out",
    meaning: "Very busy",
    korean: "완전 바쁜",
    example: "Sorry I haven't called, I've been flat out at work.",
    category: "daily-life",
  },

  // === WORK (30 phrases) ===
  {
    phrase: "How're ya going?",
    meaning: "How are you? (common workplace greeting)",
    korean: "어떻게 지내세요? (직장 인사)",
    example: "Mornin', how're ya going today?",
    category: "work",
  },
  {
    phrase: "Fair dinkum",
    meaning: "Genuine / True / Honestly",
    korean: "진짜로 / 정말이야",
    example: "Fair dinkum, that was the best presentation I've seen.",
    category: "work",
  },
  {
    phrase: "Stoked",
    meaning: "Very pleased / Thrilled",
    korean: "완전 신난 / 너무 기쁜",
    example: "I'm stoked we got that contract signed.",
    category: "work",
  },
  {
    phrase: "Choc-a-block",
    meaning: "Completely full / Packed",
    korean: "가득 찬",
    example: "My schedule is choc-a-block this week.",
    category: "work",
  },
  {
    phrase: "She'll be right",
    meaning: "Everything will be fine / Don't worry",
    korean: "괜찮을 거야 / 걱정 마",
    example: "The report isn't perfect but she'll be right.",
    category: "work",
  },
  {
    phrase: "Ripper",
    meaning: "Excellent / Great thing",
    korean: "최고야 / 대단해",
    example: "That's a ripper idea for the project!",
    category: "work",
  },
  {
    phrase: "Whinge",
    meaning: "Complain (often about something minor)",
    korean: "불평하다 / 푸념하다",
    example: "Stop whinging about the coffee machine and just make a cup.",
    category: "work",
  },
  {
    phrase: "Keen",
    meaning: "Eager / Enthusiastic",
    korean: "열정적인 / 원하는",
    example: "I'm keen to get started on the new system rollout.",
    category: "work",
  },
  {
    phrase: "Up to scratch",
    meaning: "Meeting the required standard",
    korean: "기준에 맞는",
    example: "Your work this quarter hasn't been up to scratch.",
    category: "work",
  },
  {
    phrase: "Budge up",
    meaning: "Move over / Make room",
    korean: "좀 비켜줘 / 자리 좀 줘",
    example: "Budge up a bit so I can sit down too.",
    category: "work",
  },
  {
    phrase: "Crack on",
    meaning: "Continue / Get on with it",
    korean: "계속하다 / 진행하다",
    example: "Alright team, let's crack on with the meeting.",
    category: "work",
  },
  {
    phrase: "Hard yakka",
    meaning: "Hard work / Hard labour",
    korean: "힘든 일 / 고된 노동",
    example: "Moving those boxes all day was hard yakka.",
    category: "work",
  },
  {
    phrase: "A few roos loose in the top paddock",
    meaning: "A bit crazy / Not thinking clearly",
    korean: "약간 정신이 나간",
    example: "He's got a few roos loose in the top paddock if he thinks that plan will work.",
    category: "work",
  },
  {
    phrase: "Dag",
    meaning: "Uncool person (affectionate)",
    korean: "촌스러운 사람 (애정 섞인)",
    example: "You absolute dag — wearing socks with sandals to work!",
    category: "work",
  },
  {
    phrase: "Cuppa",
    meaning: "A cup of tea or coffee",
    korean: "차 / 커피 한잔",
    example: "Let's grab a cuppa and chat about the proposal.",
    category: "work",
  },
  {
    phrase: "Bikkie time",
    meaning: "Tea/coffee break with biscuits",
    korean: "간식 타임 (커피+과자)",
    example: "It's bikkie time — who wants a Tim Tam?",
    category: "work",
  },
  {
    phrase: "Dunny",
    meaning: "Toilet / Bathroom",
    korean: "화장실",
    example: "The dunny is down the hall on the left.",
    category: "work",
  },
  {
    phrase: "Dob in",
    meaning: "Report someone / Snitch",
    korean: "고자질하다",
    example: "Someone dobbed me in for taking a long lunch.",
    category: "work",
  },
  {
    phrase: "Ticket",
    meaning: "Fine / Penalty notice (or literal ticket)",
    korean: "범칙금 / 티켓",
    example: "Parking in that spot will get you a ticket.",
    category: "work",
  },
  {
    phrase: "Letter of the law",
    meaning: "Exactly following rules",
    korean: "규정을 엄격히 지키는",
    example: "Our manager follows the letter of the law on break times.",
    category: "work",
  },
  {
    phrase: "Six and two threes",
    meaning: "Six of one, half a dozen of the other — same difference",
    korean: "똑같은 / 거기서 거기",
    example: "Doing it today or tomorrow is six and two threes.",
    category: "work",
  },
  {
    phrase: "You're dreaming",
    meaning: "You're being unrealistic",
    korean: "꿈꾸는 거야 / 현실적이지 않아",
    example: "You want Friday off too? You're dreaming.",
    category: "work",
  },
  {
    phrase: "Sickie",
    meaning: "Sick day (sometimes a fake one)",
    korean: "병가 (가짜 병가 포함)",
    example: "He's been taking too many sickies on Mondays.",
    category: "work",
  },
  {
    phrase: "Get the sack",
    meaning: "Be fired / Dismissed",
    korean: "해고되다",
    example: "If you're late again, you'll get the sack.",
    category: "work",
  },
  {
    phrase: "Bludge",
    meaning: "Laze around / Avoid work",
    korean: "빈둥거리다 / 일을 게을리하다",
    example: "Stop bludging and help us unload the truck.",
    category: "work",
  },
  {
    phrase: "Nuddy",
    meaning: "Naked (nude)",
    korean: "벌거벗은 / 알몸의",
    example: "Changing rooms — no wandering around in the nuddy!",
    category: "work",
  },
  {
    phrase: "Coorie",
    meaning: "To cuddle / snuggle (but also a work break vibe)",
    korean: "꼭 껴안다",
    example: "Not commonly used at work, but in some contexts means relaxing.",
    category: "work",
  },
  {
    phrase: "Smoko",
    meaning: "Short break (originally for smokers, now anyone)",
    korean: "짧은 휴식 시간",
    example: "I'm heading out for smoko — want anything?",
    category: "work",
  },
  {
    phrase: "Rostered day off (RDO)",
    meaning: "A scheduled day off in a work cycle",
    korean: "예정된 휴무일",
    example: "I've got an RDO next Monday — long weekend!",
    category: "work",
  },
  {
    phrase: "Award rate",
    meaning: "Minimum hourly wage set by industry",
    korean: "업종별 최저 시급",
    example: "Check the award rate for hospitality workers before you take the job.",
    category: "work",
  },

  // === SOCIAL (30 phrases) ===
  {
    phrase: "Mate",
    meaning: "Friend / Buddy / Pal",
    korean: "친구 / 동료",
    example: "Cheers mate, appreciate it!",
    category: "social",
  },
  {
    phrase: "Legend",
    meaning: "An amazing person",
    korean: "대단한 사람",
    example: "You're a legend for helping me move house.",
    category: "social",
  },
  {
    phrase: "Good onya",
    meaning: "Good for you / Well done",
    korean: "잘했어 / 대단해",
    example: "You finished the marathon? Good onya!",
    category: "social",
  },
  {
    phrase: "Bloody oath",
    meaning: "Absolutely / Yes, definitely!",
    korean: "그럼요 / 당연하죠!",
    example: "Are we going to the pub after work? — Bloody oath!",
    category: "social",
  },
  {
    phrase: "Yeah nah",
    meaning: "No (polite disagreement or refusal)",
    korean: "아니요 (정중한 거절)",
    example: "Wanna grab a beer? — Yeah nah, I've got an early start.",
    category: "social",
  },
  {
    phrase: "Nah yeah",
    meaning: "Yes (agreeing after thinking)",
    korean: "응 그래 (생각 후 동의)",
    example: "D'you reckon the movie was good? — Nah yeah, it was alright.",
    category: "social",
  },
  {
    phrase: "Too easy",
    meaning: "No problem / Very easy",
    korean: "쉬워요 / 문제없어요",
    example: "Can you grab my bag? — Too easy.",
    category: "social",
  },
  {
    phrase: "Chuck a sickie",
    meaning: "Take a fake sick day",
    korean: "가짜 병가를 내다",
    example: "We could chuck a sickie and go to the beach.",
    category: "social",
  },
  {
    phrase: "Rellies",
    meaning: "Relatives / Family members",
    korean: "친척",
    example: "We're visiting the rellies in Newcastle this weekend.",
    category: "social",
  },
  {
    phrase: "Bogan",
    meaning: "An uncultured or unsophisticated person (stereotypical 'ocker')",
    korean: "촌뜨기 / 무식한 사람",
    example: "He's a bit of a bogan but he's a good bloke.",
    category: "social",
  },
  {
    phrase: "Bloke",
    meaning: "A man / Guy",
    korean: "남자 / 사내",
    example: "He's a top bloke — always helps out.",
    category: "social",
  },
  {
    phrase: "Sheila",
    meaning: "A woman (somewhat dated but still used playfully)",
    korean: "여자 (약간 구식이지만 장난스럽게 사용)",
    example: "That sheila's a ripper surfer.",
    category: "social",
  },
  {
    phrase: "Spit the dummy",
    meaning: "Get very angry / Throw a tantrum",
    korean: "화를 내다 / 짜증내다",
    example: "He spat the dummy when he lost the game.",
    category: "social",
  },
  {
    phrase: "Fair go",
    meaning: "Give someone a chance / Be reasonable",
    korean: "기회를 줘 / 합리적으로 굴어",
    example: "Fair go mate, I only just got here!",
    category: "social",
  },
  {
    phrase: "Have a crack",
    meaning: "Try / Attempt something",
    korean: "시도하다",
    example: "I'll have a crack at fixing the sink myself.",
    category: "social",
  },
  {
    phrase: "Hard lines",
    meaning: "Bad luck / Tough luck",
    korean: "안됐네 / 운이 없네",
    example: "You missed the bus? Hard lines.",
    category: "social",
  },
  {
    phrase: "Rage",
    meaning: "A big party / To party hard",
    korean: "신나는 파티 / 마구 놀다",
    example: "We're going to rage at the festival this weekend.",
    category: "social",
  },
  {
    phrase: "Mad",
    meaning: "Very good / Cool (slang)",
    korean: "완전 좋아 / 대박",
    example: "That gig was mad! Best band I've seen.",
    category: "social",
  },
  {
    phrase: "Ripper",
    meaning: "Really great / Fantastic",
    korean: "진짜 좋아",
    example: "We had a ripper time at the BBQ.",
    category: "social",
  },
  {
    phrase: "Suss",
    meaning: "Suspicious / Check something out (verb)",
    korean: "수상한 / 살펴보다",
    example: "That guy looks suss. Let's suss him out.",
    category: "social",
  },
  {
    phrase: "Woop woop",
    meaning: "The middle of nowhere / A remote area",
    korean: "외딴 곳 / 시골",
    example: "My aunt lives out woop woop — takes hours to get there.",
    category: "social",
  },
  {
    phrase: "Kick the bucket",
    meaning: "To die (humorous)",
    korean: "죽다 (우스운 표현)",
    example: "The old goldfish kicked the bucket last night.",
    category: "social",
  },
  {
    phrase: "Pull your head in",
    meaning: "Stop being annoying / Shut up",
    korean: "좀 조용히 해 / 착각하지 마",
    example: "Pull your head in mate, nobody asked you.",
    category: "social",
  },
  {
    phrase: "Give it a burl",
    meaning: "Give it a try",
    korean: "한번 해봐",
    example: "I've never kayaked before but I'll give it a burl.",
    category: "social",
  },
  {
    phrase: "Spewin'",
    meaning: "Very annoyed / Disappointed",
    korean: "완전 열받은 / 속상한",
    example: "I'm spewin' I missed the concert tickets.",
    category: "social",
  },
  {
    phrase: "Get off my back",
    meaning: "Stop bothering / nagging me",
    korean: "잔소리 그만해 / 좀 내버려둬",
    example: "Get off my back, I'll do it when I'm ready.",
    category: "social",
  },
  {
    phrase: "Stiff",
    meaning: "Unlucky (in a mild way)",
    korean: "운이 없는",
    example: "You got a flat tyre? That's stiff.",
    category: "social",
  },
  {
    phrase: "Chunder",
    meaning: "To vomit",
    korean: "토하다",
    example: "He chundered after too many beers at the pub.",
    category: "social",
  },
  {
    phrase: "Froth",
    meaning: "Be very excited / Pumped",
    korean: "완전 신나다",
    example: "I'm frothing for the footy grand final this weekend!",
    category: "social",
  },
  {
    phrase: "Cactus",
    meaning: "Broken / Not working / Dead",
    korean: "고장 난 / 망가진",
    example: "My phone went cactus after I dropped it in the pool.",
    category: "social",
  },

  // === MEDIA (30 phrases) ===
  {
    phrase: "Footy",
    meaning: "Football (usually AFL or Rugby League depending on state)",
    korean: "풋볼 (AFL 또는 럭비 리그)",
    example: "Are you watching the footy tonight? Go the Blues!",
    category: "media",
  },
  {
    phrase: "The Ashes",
    meaning: "The famous cricket series between Australia and England",
    korean: "호주 vs 영국 크리켓 대회",
    example: "We won The Ashes again! Three-nil!",
    category: "media",
  },
  {
    phrase: "Sledge",
    meaning: "To tease / insult playfully (especially in sports)",
    korean: "약 올리다 (스포츠에서)",
    example: "The crowd was sledging the batsman all afternoon.",
    category: "media",
  },
  {
    phrase: "Tip",
    meaning: "Prediction (especially for sports results)",
    korean: "예측 (스포츠 결과)",
    example: "Who's your tip for the Melbourne Cup?",
    category: "media",
  },
  {
    phrase: "Garbo",
    meaning: "Garbage collector / Bin day",
    korean: "쓰레기 수거일 / 수거원",
    example: "Don't forget to put the bins out — garbo comes Thursday.",
    category: "media",
  },
  {
    phrase: "Postie",
    meaning: "Postman / Postal delivery worker",
    korean: "우편 배달부",
    example: "The postie's already come — there's a parcel for you.",
    category: "media",
  },
  {
    phrase: "Journo",
    meaning: "Journalist",
    korean: "기자",
    example: "The journo from Channel 9 is doing a story on our suburb.",
    category: "media",
  },
  {
    phrase: "Tradie",
    meaning: "Tradesperson (builder, electrician, plumber, etc.)",
    korean: "기술자 (건축, 전기, 배관 등)",
    example: "The tradies are starting on the renovation tomorrow.",
    category: "media",
  },
  {
    phrase: "Ambo",
    meaning: "Ambulance / Paramedic",
    korean: "구급차 / 구급대원",
    example: "Quick, call an ambo — someone's been hurt!",
    category: "media",
  },
  {
    phrase: "Sanger",
    meaning: "Sandwich (also re-listed here as it's common in social media)",
    korean: "샌드위치",
    example: "Check out the sanger I got from this cafe — unreal!",
    category: "media",
  },
  {
    phrase: "On the box",
    meaning: "On TV",
    korean: "TV에서 방영 중인",
    example: "What's on the box tonight? Anything good?",
    category: "media",
  },
  {
    phrase: "Do a Bradbury",
    meaning: "Win unexpectedly (from Steven Bradbury's 2002 gold)",
    korean: "뜻밖에 이기다 / 운으로 이기다",
    example: "Our team did a Bradbury and snuck into the finals.",
    category: "media",
  },
  {
    phrase: "Going viral",
    meaning: "Spreading rapidly online",
    korean: "바이럴 되다",
    example: "That video of the quokka went viral on TikTok.",
    category: "media",
  },
  {
    phrase: "DM",
    meaning: "Direct Message",
    korean: "다이렉트 메시지",
    example: "DM me the details and I'll check it out.",
    category: "media",
  },
  {
    phrase: "Slide into DMs",
    meaning: "Send someone a private message (often romantically)",
    korean: "DM 보내다 (종종 이성적으로)",
    example: "He slid into her DMs and now they're dating.",
    category: "media",
  },
  {
    phrase: "Finsta",
    meaning: "Fake Instagram account (private, for close friends)",
    korean: "가짜 인스타그램 계정 (친한 친구용)",
    example: "Follow my finsta for the real content.",
    category: "media",
  },
  {
    phrase: "Rinsta",
    meaning: "Real Instagram account (public-facing)",
    korean: "진짜 인스타그램 계정 (대중 공개용)",
    example: "I only post my best photos on my rinsta.",
    category: "media",
  },
  {
    phrase: "Ghost",
    meaning: "To suddenly stop all communication",
    korean: "잠수 타다 / 연락 끊다",
    example: "We went on three dates and then she ghosted me.",
    category: "media",
  },
  {
    phrase: "Stan",
    meaning: "An obsessive fan (from Eminem song)",
    korean: "열성 팬",
    example: "I'm a total stan of that Australian singer.",
    category: "media",
  },
  {
    phrase: "Ratio",
    meaning: "When replies outnumber likes (bad for the original post)",
    korean: "댓글이 좋아요보다 많음 (안 좋은 의미)",
    example: "That take was so bad they got ratio'd into oblivion.",
    category: "media",
  },
  {
    phrase: "Banger",
    meaning: "A very good song / track",
    korean: "명곡 / 대박 노래",
    example: "This new album is full of bangers.",
    category: "media",
  },
  {
    phrase: "Aussie rules footy",
    meaning: "Australian Rules Football (AFL)",
    korean: "호주식 풋볼 (AFL)",
    example: "Aussie rules footy is the most popular sport in Victoria.",
    category: "media",
  },
  {
    phrase: "Spill the tea",
    meaning: "Share gossip / Reveal drama",
    korean: "가십을 털어놓다",
    example: "Spill the tea about what happened at the party!",
    category: "media",
  },
  {
    phrase: "Lit",
    meaning: "Amazing / Exciting / Fun",
    korean: "완전 신나는 / 대박",
    example: "The concert was lit — best night ever!",
    category: "media",
  },
  {
    phrase: "Cap / No cap",
    meaning: "Lie / No lie (internet slang now used by Australians too)",
    korean: "거짓말 / 진짜로",
    example: "No cap, that was the best burger I've ever had.",
    category: "media",
  },
  {
    phrase: "Sus",
    meaning: "Suspicious / Shady",
    korean: "수상한",
    example: "That account looks sus — probably a bot.",
    category: "media",
  },
  {
    phrase: "FYP",
    meaning: "For You Page (TikTok homepage feed)",
    korean: "틱톡 메인 피드",
    example: "This recipe keeps showing up on my FYP.",
    category: "media",
  },
  {
    phrase: "OOMF",
    meaning: "One Of My Followers",
    korean: "내 팔로워 중 한 명",
    example: "OOMF posted the funniest meme today.",
    category: "media",
  },
  {
    phrase: "Lowkey",
    meaning: "Quietly / Secretly / Sort of",
    korean: "은근히 / 슬쩍",
    example: "I'm lowkey obsessed with this K-drama.",
    category: "media",
  },
  {
    phrase: "Highkey",
    meaning: "Openly / Very much",
    korean: "완전 / 대놓고",
    example: "I highkey need a coffee right now.",
    category: "media",
  },
];
