export interface Resource {
  name: string;
  description: string;
  korean: string;
  url: string;
  category: "government" | "korean-community" | "education" | "healthcare" | "emergency";
}

export const resources: Resource[] = [
  // === GOVERNMENT SERVICES ===
  {
    name: "Service NSW",
    description: "NSW Government services — driver licence, rego, fines, vouchers",
    korean: "NSW 주정부 서비스 — 운전면허, 자동차 등록, 벌금, 바우처",
    url: "https://www.service.nsw.gov.au",
    category: "government",
  },
  {
    name: "Services Australia",
    description: "Centrelink, Medicare, child support, and other federal services",
    korean: "센터링크, 메디케어, 양육비 등 연방 서비스",
    url: "https://www.servicesaustralia.gov.au",
    category: "government",
  },
  {
    name: "Australian Taxation Office (ATO)",
    description: "Tax returns, TFN, superannuation, business tax",
    korean: "세금 신고, TFN, 퇴직연금, 사업 세금",
    url: "https://www.ato.gov.au",
    category: "government",
  },
  {
    name: "Fair Work Ombudsman",
    description: "Workplace rights, pay rates, leave entitlements, complaints",
    korean: "직장 권리, 임금, 휴가, 고충 처리",
    url: "https://www.fairwork.gov.au",
    category: "government",
  },
  {
    name: "Department of Home Affairs",
    description: "Visa applications, immigration, citizenship",
    korean: "비자 신청, 이민, 시민권",
    url: "https://homeaffairs.gov.au",
    category: "government",
  },
  {
    name: "NSW Fair Trading",
    description: "Tenancy rights, rental bonds, complaints about businesses",
    korean: "임대차 권리, 보증금, 소비자 보호",
    url: "https://www.fairtrading.nsw.gov.au",
    category: "government",
  },
  {
    name: "Australian Electoral Commission (AEC)",
    description: "Voter registration and election information",
    korean: "선거인 등록 및 선거 정보",
    url: "https://www.aec.gov.au",
    category: "government",
  },

  // === KOREAN COMMUNITY ===
  {
    name: "Korean Society of Sydney (KSS)",
    description: "Community events, cultural programs, and support for Koreans in Sydney",
    korean: "시드니 한인회 — 커뮤니티 행사, 문화 프로그램, 지원",
    url: "https://www.koreansociety.org.au",
    category: "korean-community",
  },
  {
    name: "Sydney Korean Church",
    description: "One of the largest Korean churches in Sydney with community services",
    korean: "시드니 한인 교회 — 다양한 커뮤니티 서비스 제공",
    url: "https://www.sydneykorean.org.au",
    category: "korean-community",
  },
  {
    name: "Korean Australian Community Services",
    description: "Support services, aged care, and cultural programs",
    korean: "호주 한인 커뮤니티 서비스 — 지원 서비스, 노인 복지",
    url: "https://www.kacs.org.au",
    category: "korean-community",
  },
  {
    name: "Korean Cultural Centre Australia",
    description: "Korean language classes, cultural events, exhibitions in Sydney CBD",
    korean: "주호주 한국문화원 — 한국어 수업, 문화 행사, 전시회",
    url: "https://www.koreanculture.org.au",
    category: "korean-community",
  },
  {
    name: "Korean Student Association of NSW",
    description: "Student groups and networks for Korean international students",
    korean: "NSW 한인 학생회 — 유학생 네트워크 및 지원",
    url: "https://www.facebook.com/KSANSW",
    category: "korean-community",
  },
  {
    name: "한인회 (Korean Association of NSW)",
    description: "Official Korean association providing legal and community support",
    korean: "NSW 한인회 — 법률 및 커뮤니티 지원 제공",
    url: "https://www.koreans.org.au",
    category: "korean-community",
  },
  {
    name: "Strathfield Korean Community",
    description: "Strathfield has one of the largest Korean populations in Sydney",
    korean: "스트라스필드 한인 커뮤니티 — 시드니 최대 한인 밀집 지역",
    url: "https://strathfield.nsw.gov.au/community",
    category: "korean-community",
  },
  {
    name: "Korean Grocery Finder",
    description: "Find Korean supermarkets and marts across Sydney",
    korean: "시드니 한인 마트 찾기",
    url: "https://www.koreangrocery.com.au",
    category: "korean-community",
  },
  {
    name: "Korean Welfare Association",
    description: "Welfare support and advice for Korean migrants and families",
    korean: "한인 복지 협회 — 이민자 및 가족 복지 지원",
    url: "https://www.koreanwelfare.org.au",
    category: "korean-community",
  },

  // === EDUCATION ===
  {
    name: "Study NSW",
    description: "Official NSW government site for international students",
    korean: "NSW 주정부 유학생 공식 정보 사이트",
    url: "https://www.study.nsw.gov.au",
    category: "education",
  },
  {
    name: "Australian Department of Education",
    description: "National education policies, student support, and accreditation",
    korean: "호주 교육부 — 국가 교육 정책, 학생 지원",
    url: "https://www.education.gov.au",
    category: "education",
  },
  {
    name: "TEQSA",
    description: "Australian higher education quality and standards regulator",
    korean: "호주 고등교육 품질 기준 기관",
    url: "https://www.teqsa.gov.au",
    category: "education",
  },
  {
    name: "ESOS Framework",
    description: "Education Services for Overseas Students — your rights as an international student",
    korean: "유학생 교육 서비스 — 유학생 권리 보호",
    url: "https://www.education.gov.au/esos-framework",
    category: "education",
  },
  {
    name: "University of Sydney",
    description: "Top Australian university in Camperdown/Darlington",
    korean: "시드니 대학교 — 캠퍼다운/달링턴 캠퍼스",
    url: "https://www.sydney.edu.au",
    category: "education",
  },
  {
    name: "UNSW Sydney",
    description: "Leading university in Kensington with strong engineering and business",
    korean: "UNSW 시드니 — 켄싱턴 캠퍼스, 공대/경영대 강세",
    url: "https://www.unsw.edu.au",
    category: "education",
  },
  {
    name: "University of Technology Sydney (UTS)",
    description: "City-based university with strong industry links",
    korean: "UTS — 시드니 도심 위치, 산업체 연계 강점",
    url: "https://www.uts.edu.au",
    category: "education",
  },
  {
    name: "Macquarie University",
    description: "University in North Ryde with strong speech pathology and business",
    korean: "매쿼리 대학교 — 노스라이드 캠퍼스",
    url: "https://www.mq.edu.au",
    category: "education",
  },
  {
    name: "TAFE NSW",
    description: "Vocational education and training across NSW",
    korean: "NSW 전문 직업 교육 기관",
    url: "https://www.tafensw.edu.au",
    category: "education",
  },
  {
    name: "Overseas Student Ombudsman",
    description: "Complaints about private education providers for international students",
    korean: "해외 학생 옴부즈맨 — 사설 교육 기관 불만 처리",
    url: "https://www.ombudsman.gov.au/how-we-can-help/overseas-students",
    category: "education",
  },
  {
    name: "IDP Education",
    description: "International education placement and IELTS testing",
    korean: "국제 교육 기관 연계 및 IELTS 시험",
    url: "https://www.idp.com/australia",
    category: "education",
  },

  // === HEALTHCARE ===
  {
    name: "Medicare Australia",
    description: "Australia's public healthcare system — get a Medicare card",
    korean: "호주 공공 의료 시스템 — 메디케어 카드 발급",
    url: "https://www.servicesaustralia.gov.au/medicare",
    category: "healthcare",
  },
  {
    name: "NSW Health",
    description: "NSW public hospitals, clinics, and health information",
    korean: "NSW 공공 병원, 클리닉, 건강 정보",
    url: "https://www.health.nsw.gov.au",
    category: "healthcare",
  },
  {
    name: "HealthDirect",
    description: "24/7 health advice and symptom checker — call 1800 022 222",
    korean: "24시간 건강 상담 — 1800 022 222",
    url: "https://www.healthdirect.gov.au",
    category: "healthcare",
  },
  {
    name: "PBS (Pharmaceutical Benefits Scheme)",
    description: "Subsidised prescription medicines for Medicare cardholders",
    korean: "처방약 할인 제도",
    url: "https://www.pbs.gov.au",
    category: "healthcare",
  },
  {
    name: "Overseas Student Health Cover (OSHC)",
    description: "Required health insurance for international students",
    korean: "유학생 건강 보험 (필수 가입)",
    url: "https://www.oshc.gov.au",
    category: "healthcare",
  },
  {
    name: "Headspace",
    description: "Free youth mental health support (12-25 years)",
    korean: "무료 청소년 정신 건강 지원 (12-25세)",
    url: "https://headspace.org.au",
    category: "healthcare",
  },
  {
    name: "Lifeline Australia",
    description: "24/7 crisis support — call 13 11 14",
    korean: "24시간 위기 상담 — 13 11 14",
    url: "https://www.lifeline.org.au",
    category: "healthcare",
  },
  {
    name: "Beyond Blue",
    description: "Mental health support — call 1300 22 4636",
    korean: "정신 건강 지원 — 1300 22 4636",
    url: "https://www.beyondblue.org.au",
    category: "healthcare",
  },
  {
    name: "Poisons Information Centre",
    description: "Emergency poison advice — call 13 11 26",
    korean: "중독 응급 상담 — 13 11 26",
    url: "https://www.poisonsinfo.nsw.gov.au",
    category: "healthcare",
  },
  {
    name: "NURSE-ON-CALL",
    description: "Free 24/7 telephone health advice from a registered nurse",
    korean: "무료 24시간 전화 건강 상담 (등록 간호사)",
    url: "tel:1300606024",
    category: "healthcare",
  },

  // === EMERGENCY ===
  {
    name: "Emergency — Police, Fire, Ambulance",
    description: "Call 000 for life-threatening emergencies",
    korean: "응급 — 경찰, 소방, 구급차: 000",
    url: "https://www.police.nsw.gov.au",
    category: "emergency",
  },
  {
    name: "Police Assistance Line",
    description: "Non-urgent police matters — call 131 444",
    korean: "비응급 경찰 상담 — 131 444",
    url: "https://www.police.nsw.gov.au/contact_us",
    category: "emergency",
  },
  {
    name: "Crime Stoppers NSW",
    description: "Report crime anonymously — call 1800 333 000",
    korean: "익명 범죄 신고 — 1800 333 000",
    url: "https://www.nsw.crimestoppers.com.au",
    category: "emergency",
  },
  {
    name: "SES (State Emergency Service)",
    description: "Emergency help for floods, storms, and tsunamis — call 132 500",
    korean: "홍수, 폭풍, 쓰나미 응급 지원 — 132 500",
    url: "https://www.ses.nsw.gov.au",
    category: "emergency",
  },
  {
    name: "NSW Bush Fire Info",
    description: "Real-time bushfire warnings and updates",
    korean: "실시간 산불 경보 및 업데이트",
    url: "https://www.rfs.nsw.gov.au/fire-information",
    category: "emergency",
  },
  {
    name: "Translating and Interpreting Service (TIS)",
    description: "Free interpreter service for non-English speakers — call 131 450",
    korean: "무료 통역 서비스 — 131 450",
    url: "https://www.tisnational.gov.au",
    category: "emergency",
  },
  {
    name: "National Relay Service",
    description: "Phone service for people who are deaf or hard of hearing",
    korean: "청각 장애인 전화 서비스",
    url: "https://www.relayservice.gov.au",
    category: "emergency",
  },
  {
    name: "Australian Consular Emergency Centre",
    description: "Consular assistance for Australians overseas — call 1300 555 135",
    korean: "해외 호주인 영사 지원",
    url: "https://www.smartraveller.gov.au",
    category: "emergency",
  },
];
