// app/destinations/i18n.ts — GENERATED by cache/scratch/build_dest_templates.py.
//
// Title and FAQ-question templates per locale. Both were English on every locale, so a
// Japanese search result read "Kiama: 2hrs from Sydney — Beaches, Walks & Things to Do".
// {name} and {time} are filled at render time from the destination's own translations.
//
// Non-ASCII is written as \uXXXX escapes — escapes cannot be mangled by the write path.

import type { Lang } from "@/lib/locale";
import type { TripLength } from "./data";

export type DestinationTemplates = {
  title_time: string;
  title_plain: string;
  faq_days: string;
  faq_besttime: string;
  faq_gettingthere: string;
};

export const DEST_TEMPLATES: Record<Lang, DestinationTemplates> = {
  en: {
    title_time: "{name}: {time} from Sydney \u2014 Beaches, Walks & Things to Do",
    title_plain: "{name} \u2014 Beaches, Walks & Things to Do",
    faq_days: "How many days do I need in {name}?",
    faq_besttime: "When is the best time to visit {name}?",
    faq_gettingthere: "How do I get to {name} from Sydney?",
  },
  ja: {
    title_time: "\u30b7\u30c9\u30cb\u30fc\u304b\u3089{time}\u306e{name}\uff5c\u30d3\u30fc\u30c1\u30fb\u30a6\u30a9\u30fc\u30ad\u30f3\u30b0\u30fb\u89b3\u5149\u30b9\u30dd\u30c3\u30c8",
    title_plain: "{name}\uff5c\u30d3\u30fc\u30c1\u30fb\u30a6\u30a9\u30fc\u30ad\u30f3\u30b0\u30fb\u89b3\u5149\u30b9\u30dd\u30c3\u30c8",
    faq_days: "{name}\u306e\u89b3\u5149\u306b\u306f\u4f55\u65e5\u5fc5\u8981\u3067\u3059\u304b\uff1f",
    faq_besttime: "{name}\u306e\u30d9\u30b9\u30c8\u30b7\u30fc\u30ba\u30f3\u306f\u3044\u3064\u3067\u3059\u304b\uff1f",
    faq_gettingthere: "\u30b7\u30c9\u30cb\u30fc\u304b\u3089{name}\u3078\u306f\u3069\u3046\u3084\u3063\u3066\u884c\u304d\u307e\u3059\u304b\uff1f",
  },
  zh: {
    title_time: "{name}\uff1a\u8ddd\u6089\u5c3c{time} \u2014 \u6d77\u6ee9\u3001\u5f92\u6b65\u4e0e\u73a9\u4e50\u6307\u5357",
    title_plain: "{name} \u2014 \u6d77\u6ee9\u3001\u5f92\u6b65\u4e0e\u73a9\u4e50\u6307\u5357",
    faq_days: "\u5728{name}\u9700\u8981\u73a9\u51e0\u5929\uff1f",
    faq_besttime: "\u4ec0\u4e48\u65f6\u5019\u53bb{name}\u6700\u597d\uff1f",
    faq_gettingthere: "\u4ece\u6089\u5c3c\u600e\u4e48\u53bb{name}\uff1f",
  },
  ko: {
    title_time: "\uc2dc\ub4dc\ub2c8\uc5d0\uc11c {time} \uac70\ub9ac, {name} \u2014 \ud574\ubcc0\uacfc \uc0b0\ucc45\ub85c, \uc990\uae38 \uac70\ub9ac",
    title_plain: "{name} \u2014 \ud574\ubcc0\uacfc \uc0b0\ucc45\ub85c, \uc990\uae38 \uac70\ub9ac",
    faq_days: "{name}\uc5d0\uc11c \uba70\uce60\uc774\ub098 \ud544\uc694\ud55c\uac00\uc694?",
    faq_besttime: "{name} \ubc29\ubb38\ud558\uae30 \uac00\uc7a5 \uc88b\uc740 \uc2dc\uae30\ub294 \uc5b8\uc81c\uc778\uac00\uc694?",
    faq_gettingthere: "\uc2dc\ub4dc\ub2c8\uc5d0\uc11c {name}\uae4c\uc9c0 \uac00\ub294 \ubc29\ubc95\uc740 \ubb34\uc5c7\uc778\uac00\uc694?",
  },
};

// The internal-linking invitation sentences, one per trip length. These existed only in
// English and Korean, so the Japanese and Chinese pages printed the English sentence.
export const RELATE_TEMPLATES: Record<"en" | "ja" | "zh", Record<TripLength, string>> = {
  en: {
    day: "Build a {name} day trip out of a Sydney base \u2014 pick the train, pick the morning, pick the lookout.",
    weekend: "Plan a {name} weekend from Sydney \u2014 overnight, two meals, the main thing you came for, and a Sunday-morning walk back.",
    longer: "{name} is worth 3+ days \u2014 a longer stay lets you catch the second-day-favourite spots that day-trippers miss.",
    far: "{name} is a real trip \u2014 fly or drive, give it a week, and slow down enough to actually enjoy the place.",
  },
  ja: {
    day: "\u30b7\u30c9\u30cb\u30fc\u3092\u62e0\u70b9\u306b{name}\u3078\u306e\u65e5\u5e30\u308a\u65c5\u3092\u8a08\u753b\u3057\u307e\u3057\u3087\u3046 \u2014 \u96fb\u8eca\u3092\u9078\u3073\u3001\u671d\u306e\u6642\u9593\u5e2f\u3092\u9078\u3073\u3001\u5c55\u671b\u53f0\u3092\u9078\u3076\u3002",
    weekend: "\u30b7\u30c9\u30cb\u30fc\u304b\u3089{name}\u306e\u9031\u672b\u3092\u8a08\u753b\u3057\u307e\u3057\u3087\u3046 \u2014 \u4e00\u6cca\u3001\u4e8c\u5ea6\u306e\u98df\u4e8b\u3001\u76ee\u5f53\u3066\u306e\u898b\u3069\u3053\u308d\u3001\u305d\u3057\u3066\u65e5\u66dc\u306e\u671d\u306b\u6b69\u3044\u3066\u623b\u308b\u9053\u306e\u308a\u3002",
    longer: "{name}\u306f3\u65e5\u4ee5\u4e0a\u304b\u3051\u308b\u4fa1\u5024\u304c\u3042\u308a\u307e\u3059 \u2014 \u9577\u304f\u6ede\u5728\u3059\u308c\u3070\u3001\u65e5\u5e30\u308a\u5ba2\u304c\u898b\u9003\u3059\u4e8c\u65e5\u76ee\u306e\u304a\u6c17\u306b\u5165\u308a\u30b9\u30dd\u30c3\u30c8\u306b\u3082\u51fa\u4f1a\u3048\u307e\u3059\u3002",
    far: "{name}\u306f\u672c\u683c\u7684\u306a\u65c5\u3067\u3059 \u2014 \u98db\u884c\u6a5f\u304b\u8eca\u3067\u5411\u304b\u3044\u30011\u9031\u9593\u307b\u3069\u304b\u3051\u3066\u3001\u3053\u306e\u571f\u5730\u3092\u3086\u3063\u304f\u308a\u5473\u308f\u3044\u307e\u3057\u3087\u3046\u3002",
  },
  zh: {
    day: "\u4ee5\u6089\u5c3c\u4e3a\u57fa\u5730\u5b89\u6392\u4e00\u8d9f{name}\u4e00\u65e5\u6e38\u2014\u2014\u6311\u4e00\u73ed\u706b\u8f66\uff0c\u6311\u4e00\u4e2a\u6e05\u6668\uff0c\u6311\u4e00\u5904\u89c2\u666f\u53f0\u3002",
    weekend: "\u4ece\u6089\u5c3c\u51fa\u53d1\u89c4\u5212\u4e00\u4e2a{name}\u5468\u672b\u2014\u2014\u4f4f\u4e0a\u4e00\u665a\uff0c\u5403\u4e24\u987f\u996d\uff0c\u628a\u6700\u60f3\u770b\u7684\u90a3\u5904\u770b\u591f\uff0c\u5468\u65e5\u65e9\u4e0a\u518d\u6162\u6162\u8d70\u56de\u6765\u3002",
    longer: "{name}\u503c\u5f97\u5f85\u4e0a3\u5929\u4ee5\u4e0a\u2014\u2014\u591a\u7559\u51e0\u5929\uff0c\u624d\u80fd\u901b\u5230\u4e00\u65e5\u6e38\u5ba2\u9519\u8fc7\u3001\u7b2c\u4e8c\u5929\u624d\u6210\u4e3a\u5fc3\u5934\u597d\u7684\u90a3\u4e9b\u5730\u65b9\u3002",
    far: "{name}\u7b97\u5f97\u4e0a\u4e00\u8d9f\u771f\u6b63\u7684\u65c5\u884c\u2014\u2014\u5750\u98de\u673a\u6216\u81ea\u9a7e\uff0c\u7559\u51fa\u4e00\u5468\u65f6\u95f4\uff0c\u6162\u4e0b\u6765\u624d\u80fd\u771f\u6b63\u4eab\u53d7\u8fd9\u4e2a\u5730\u65b9\u3002",
  },
};
