// app/destinations/i18n.ts — GENERATED by cache/scratch/build_dest_templates.py.
//
// Title and FAQ-question templates per locale. Both were English on every locale, so a
// Japanese search result read "Kiama: 2hrs from Sydney — Beaches, Walks & Things to Do".
// {name} and {time} are filled at render time from the destination's own translations.
//
// Non-ASCII is written as \uXXXX escapes — escapes cannot be mangled by the write path.

import type { Lang } from "@/lib/locale";

export type DestinationTemplates = {
  title_time: string;
  title_plain: string;
  faq_days: string;
  faq_besttime: string;
  faq_gettingthere: string;
};

export const DEST_TEMPLATES: Record<Lang, DestinationTemplates> = {
  en: {
    title_time: "{name}: {time} from Sydney \u2014 Beaches, Walks & Things to Do",
    title_plain: "{name} \u2014 Beaches, Walks & Things to Do",
    faq_days: "How many days do I need in {name}?",
    faq_besttime: "When is the best time to visit {name}?",
    faq_gettingthere: "How do I get to {name} from Sydney?",
  },
  ja: {
    title_time: "\u30b7\u30c9\u30cb\u30fc\u304b\u3089{time}\u306e{name}\uff5c\u30d3\u30fc\u30c1\u30fb\u30a6\u30a9\u30fc\u30ad\u30f3\u30b0\u30fb\u89b3\u5149\u30b9\u30dd\u30c3\u30c8",
    title_plain: "{name}\uff5c\u30d3\u30fc\u30c1\u30fb\u30a6\u30a9\u30fc\u30ad\u30f3\u30b0\u30fb\u89b3\u5149\u30b9\u30dd\u30c3\u30c8",
    faq_days: "{name}\u306e\u89b3\u5149\u306b\u306f\u4f55\u65e5\u5fc5\u8981\u3067\u3059\u304b\uff1f",
    faq_besttime: "{name}\u306e\u30d9\u30b9\u30c8\u30b7\u30fc\u30ba\u30f3\u306f\u3044\u3064\u3067\u3059\u304b\uff1f",
    faq_gettingthere: "\u30b7\u30c9\u30cb\u30fc\u304b\u3089{name}\u3078\u306f\u3069\u3046\u3084\u3063\u3066\u884c\u304d\u307e\u3059\u304b\uff1f",
  },
  zh: {
    title_time: "{name}\uff1a\u8ddd\u6089\u5c3c{time} \u2014 \u6d77\u6ee9\u3001\u5f92\u6b65\u4e0e\u73a9\u4e50\u6307\u5357",
    title_plain: "{name} \u2014 \u6d77\u6ee9\u3001\u5f92\u6b65\u4e0e\u73a9\u4e50\u6307\u5357",
    faq_days: "\u5728{name}\u9700\u8981\u73a9\u51e0\u5929\uff1f",
    faq_besttime: "\u4ec0\u4e48\u65f6\u5019\u53bb{name}\u6700\u597d\uff1f",
    faq_gettingthere: "\u4ece\u6089\u5c3c\u600e\u4e48\u53bb{name}\uff1f",
  },
  ko: {
    title_time: "\uc2dc\ub4dc\ub2c8\uc5d0\uc11c {time} \uac70\ub9ac, {name} \u2014 \ud574\ubcc0\uacfc \uc0b0\ucc45\ub85c, \uc990\uae38 \uac70\ub9ac",
    title_plain: "{name} \u2014 \ud574\ubcc0\uacfc \uc0b0\ucc45\ub85c, \uc990\uae38 \uac70\ub9ac",
    faq_days: "{name}\uc5d0\uc11c \uba70\uce60\uc774\ub098 \ud544\uc694\ud55c\uac00\uc694?",
    faq_besttime: "{name} \ubc29\ubb38\ud558\uae30 \uac00\uc7a5 \uc88b\uc740 \uc2dc\uae30\ub294 \uc5b8\uc81c\uc778\uac00\uc694?",
    faq_gettingthere: "\uc2dc\ub4dc\ub2c8\uc5d0\uc11c {name}\uae4c\uc9c0 \uac00\ub294 \ubc29\ubc95\uc740 \ubb34\uc5c7\uc778\uac00\uc694?",
  },
};
